
package Tareasimulacionhilos;

import java.awt.Color;


public class PersonasEntrando extends javax.swing.JFrame {
    int personas1;
    int personas2;
    int bol;
    Thread Entrada = new Thread(){
    
        public void run(){
            
            try{
                for(personas1=0;personas1<=500;personas1+=20){
                jProgressBar1.setValue(personas1);
                jProgressBar1.setMaximum(500);
                 entrada1.setText("Se Acabaron las Entradas Mas Suerte la Proxima : " + personas1);
                Entrada.sleep(100);
                jProgressBar1.setBackground(Color.CYAN);
                }
                
            }catch(Exception e){
                
                    }
        }
    
    };
   
    Thread Entrada2 = new Thread(){
    
        public void run(){
            
            try{
                for(personas2=0;personas2<=500;personas2+=20){
                jProgressBar2.setValue(personas2);
                jProgressBar2.setMaximum(500);
                entrada2.setText("Se Acabaron las Entradas Mas Suerte la Proxima  " + personas2);
                Entrada2.sleep(100);
                jProgressBar2.setBackground(Color.ORANGE);
               
                
                }
                
            }catch(Exception e){
                
                    }
        }
    
    };

   
    public PersonasEntrando() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        entrada1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        entrada2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Puerta 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Puerta 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Vamos a ver cuantas personas entraron con los boletos vendidos ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 480, -1));

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        entrada1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        entrada1.setText("...");
        jPanel1.add(entrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 190, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 40));

        entrada2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entrada2.setForeground(new java.awt.Color(255, 255, 255));
        entrada2.setText("...");
        jPanel1.add(entrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 660, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/interiores-en-auditorios.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 430));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Puerta 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Entrada.start();
         Entrada2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonasEntrando().setVisible(true);
            }
        });
    }
    /*
    Ayala Sanchez Andre Eduardo 5IV8 :3
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entrada1;
    private javax.swing.JLabel entrada2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
